### ISSUE TITLE
how to specify tags in a curl post api request

### ISSUE THREAD

**Issue by m040601** [riichard/pocket-sh-add#2]
Thank you for your work on this fantastic simple and usefull tool.

It really does what it says in the can :-)

>  simple shell script, and some curl. No python installs, no dependencies, and no javascript!
> 
> Integrates fantastically with any UNIX operating system, seemlessly connects to lynx, mutt, newsbeuter, newsboat!

I'm not very skilled with neither curl nor the pocket api. But I am almost sure there must be a way  to specify "tags" to add to a URL when you want to save to getpocket.com using just curl.

Would it be possible to make this tool, optionaly read a second (or third, fourth etc) argument as tags ?

pocket-sh-add.sh $1
pocket-sh-add.sh $1 [$2 $3 ...]

if only one argument is passed, it is expected to be a URL
if 2 or more arguments are passed the 2nd, 3rd etc, are expected to be tags.

PS:  example from a python cli tool, 
pocket-cli add -u https://myarticle.com/   --tags=tech 
pocket-cli add -u https://myarticle.com/   --tags=tech,news,later
https://github.com/rakanalh/pocket-cli (archived but still working fine)

**Comment by riichard** [comment]
Thanks for the kind words @m040601, I'm also very happy with how easy it is to set up on any machine. I just pushed an update which adds the tags via the $2 parameter.

You can send $2 as a string to have it include multiple tags, separated by a comma.

**Comment by riichard** [comment]
Done such as:
```
./add.sh https://slate.com/human-interest/2019/11/50-best-nonfiction-books.html "books, nonfiction"
```

**Comment by m040601** [comment]
Perfect ! Thanks a lot. You can close it know.


Some more suggestions:

1. help

You might also consider the case where the user "forgets" to add any argument at all, no $1. In that case you could display an error message with the contents and examples of  the README. Same with an -h flag.
Example, (? bash required), https://linuxconfig.org/bash-script-display-usage-and-check-user



2. use XDG directories for token file pocketshrc and others

don't store .pocketshrc in the HOME dir. It kind of pollutes the home dir
 Use XDG config home, it would be something like, ~/.config/pocketshadd/pocketshaddrc
no need for for it to be a hidden file. 


3.  Standardize the name of the script and associate files ?

pocket-sh-add ?
or
pocketsh ?
pocketshaddrc ... etc ...

I'm suggesting this, because there are so  many pocket scripts (python based and others) each one of them with similar names and config/token files, that it's very easy to forget, mix them up and remember which  one belongs to which appplication. 

Trying out simple cli solutions for pocket I ended up with lots of  dotfiles with similar names:


dot.config/pocket/pocket.conf
dot.pocketshrc
dot.pocket-config
dot.pocket-index
etc ...

in my home dir, containing access/tokens/keys, and almost forgot which app had generated them.





> I'm also very happy with how easy it is to set up on any machine. 

yes, indeed. I wonder why your script isn't much better known on the internet.
I specially liked how you handled the oauth/token/consumerkey registration dance with getpocket.com  with shell  scripting.

**Comment by riichard** [comment]
Thanks!

Just of out curiosity, how are you using it?

**Comment by riichard** [comment]
And that’s a lot of suggestions. I like them, I’ll try to add them in the upcoming days.
