### ISSUE TITLE
Getting 401 Unauthorized error

### ISSUE THREAD

**Issue by KroccoHi** [riichard/pocket-sh-add#3]
on Linux Ubuntu. Tried authenticating with Vivaldi and Firefox same result.
![Screenshot from 2021-10-01 18-11-39](https://user-images.githubusercontent.com/41275128/135568624-434b2894-255f-42a2-a7ba-124720700278.png)

**Comment by riichard** [comment]
Hi @KroccoHi, it seems that it's not receiving a valid token in authenticate.sh, can you try [creating a new app api key at pocket](https://getpocket.com/developer/) and change the consumer token at [authenticate.sh](https://github.com/riichard/pocket-sh-add/blob/master/authenticate.sh#L3) ? I think it must've reached a limit.

**Comment by KroccoHi** [comment]
> Hi @KroccoHi, it seems that it's not receiving a valid token in authenticate.sh, can you try [creating a new app api key at pocket](https://getpocket.com/developer/) and change the consumer token at [authenticate.sh](https://github.com/riichard/pocket-sh-add/blob/master/authenticate.sh#L3) ? I think it must've reached a limit.

Thanks for the reply. I tried this and it worked great, I'm using it with [newsboat](https://github.com/newsboat/newsboat).

**Comment by riichard** [comment]
> > Hi @KroccoHi, it seems that it's not receiving a valid token in authenticate.sh, can you try [creating a new app api key at pocket](https://getpocket.com/developer/) and change the consumer token at [authenticate.sh](https://github.com/riichard/pocket-sh-add/blob/master/authenticate.sh#L3) ? I think it must've reached a limit.
> 
> 
> 
> Thanks for the reply. I tried this and it worked great, I'm using it with [newsboat](https://github.com/newsboat/newsboat).

That's great, im using it with newsboat too. It works perfect with the newsboat custom bookmark script config, and then fetch them on the pocket app on my e-reader.
